application:
  name: "qa-iewc-taxrequest"


api:
  autodiscoveryId: "18690147"  

http:
 listener:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
 request:
  host: "sb-taxrequest-papi.us-e1.cloudhub.io"
  timeout: "30000"
  port: ""
  path: "/api/tax_request"
  


  
