application:
  name: "local-iewc-taxrequest"


api:
  autodiscoveryId: "123456"  

http:
 listener:
  host: "0.0.0.0"
  port: "8083"
  timeout: "30000"
 request:
  host: "0.0.0.0"
  port: "8085"
  timeout: "30000"
  path: "api/tax_request"
  

  
  



  

