#%RAML 1.0
title: iewc-taxrequest-eapi
description: This is an Experience API(User facing API) which is exposed as website to the users.      
version: v1
protocols: [HTTP,HTTPS] 
mediaType: application/json

types:
  iewc_tax_request: !include /dataTypes/tax_request.raml
  iewc_tax_response: !include /dataTypes/tax_response.raml
  error-response: !include /exchange_modules/45fe9fe3-71e9-4c7f-99b4-aade424656d9/common-fragment/1.0.3/errorFiles/error-dataType.raml

securitySchemes: 
 clientPolicy: !include /exchange_modules/45fe9fe3-71e9-4c7f-99b4-aade424656d9/common-fragment/1.0.3/security/clientEnforcementPolicy.raml
securedBy:
  - clientPolicy
  
/tax_request:
   post:
    body:
      application/json:
        type: iewc_tax_request
        example: !include /examples/tax_request.json
    responses:
      200:
        body:
          application/json:
            type: iewc_tax_response
            example: !include /examples/tax_response.json
      401:
        body:
          application/json:
            type: error-response
            example: !include /exchange_modules/45fe9fe3-71e9-4c7f-99b4-aade424656d9/common-fragment/1.0.3/errorFiles/401error-example.json
       


    

    